/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModeSelectRouteImport } from './routes/mode-select'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVehicleVerificationRouteImport } from './routes/_app.vehicle-verification'
import { Route as AppTripEndRouteImport } from './routes/_app.trip-end'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppCustomerRouteImport } from './routes/_app.customer'
import { Route as AppBusinessRouteImport } from './routes/_app.business'
import { Route as AppBeTheOwnerRouteImport } from './routes/_app.be-the-owner'

const ModeSelectRoute = ModeSelectRouteImport.update({
  id: '/mode-select',
  path: '/mode-select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehicleVerificationRoute = AppVehicleVerificationRouteImport.update({
  id: '/vehicle-verification',
  path: '/vehicle-verification',
  getParentRoute: () => AppRoute,
} as any)
const AppTripEndRoute = AppTripEndRouteImport.update({
  id: '/trip-end',
  path: '/trip-end',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRoute = AppCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppBeTheOwnerRoute = AppBeTheOwnerRouteImport.update({
  id: '/be-the-owner',
  path: '/be-the-owner',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mode-select': typeof ModeSelectRoute
  '/be-the-owner': typeof AppBeTheOwnerRoute
  '/business': typeof AppBusinessRoute
  '/customer': typeof AppCustomerRoute
  '/history': typeof AppHistoryRoute
  '/notifications': typeof AppNotificationsRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/trip-end': typeof AppTripEndRoute
  '/vehicle-verification': typeof AppVehicleVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mode-select': typeof ModeSelectRoute
  '/be-the-owner': typeof AppBeTheOwnerRoute
  '/business': typeof AppBusinessRoute
  '/customer': typeof AppCustomerRoute
  '/history': typeof AppHistoryRoute
  '/notifications': typeof AppNotificationsRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/trip-end': typeof AppTripEndRoute
  '/vehicle-verification': typeof AppVehicleVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mode-select': typeof ModeSelectRoute
  '/_app/be-the-owner': typeof AppBeTheOwnerRoute
  '/_app/business': typeof AppBusinessRoute
  '/_app/customer': typeof AppCustomerRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/trip-end': typeof AppTripEndRoute
  '/_app/vehicle-verification': typeof AppVehicleVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mode-select'
    | '/be-the-owner'
    | '/business'
    | '/customer'
    | '/history'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/trip-end'
    | '/vehicle-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mode-select'
    | '/be-the-owner'
    | '/business'
    | '/customer'
    | '/history'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/trip-end'
    | '/vehicle-verification'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/mode-select'
    | '/_app/be-the-owner'
    | '/_app/business'
    | '/_app/customer'
    | '/_app/history'
    | '/_app/notifications'
    | '/_app/payments'
    | '/_app/profile'
    | '/_app/trip-end'
    | '/_app/vehicle-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModeSelectRoute: typeof ModeSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mode-select': {
      id: '/mode-select'
      path: '/mode-select'
      fullPath: '/mode-select'
      preLoaderRoute: typeof ModeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vehicle-verification': {
      id: '/_app/vehicle-verification'
      path: '/vehicle-verification'
      fullPath: '/vehicle-verification'
      preLoaderRoute: typeof AppVehicleVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trip-end': {
      id: '/_app/trip-end'
      path: '/trip-end'
      fullPath: '/trip-end'
      preLoaderRoute: typeof AppTripEndRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer': {
      id: '/_app/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AppCustomerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/be-the-owner': {
      id: '/_app/be-the-owner'
      path: '/be-the-owner'
      fullPath: '/be-the-owner'
      preLoaderRoute: typeof AppBeTheOwnerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBeTheOwnerRoute: typeof AppBeTheOwnerRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppCustomerRoute: typeof AppCustomerRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTripEndRoute: typeof AppTripEndRoute
  AppVehicleVerificationRoute: typeof AppVehicleVerificationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeTheOwnerRoute: AppBeTheOwnerRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppCustomerRoute: AppCustomerRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTripEndRoute: AppTripEndRoute,
  AppVehicleVerificationRoute: AppVehicleVerificationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ModeSelectRoute: ModeSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
